
import { Asset, AssetType, Industry, User, AICategory, Company, PCFProduct, DPPInspection, DataTransaction } from './types';

export const CURRENT_USER: User = {
  id: 'usr_123',
  name: 'TaeHoon, Jang',
  company: 'Korea',
  walletAddress: '0x71C...9A23',
  role: 'BOTH'
};

// --- MOCK PCF & DPP DATA ---

export const MOCK_PCF_PRODUCTS: PCFProduct[] = [
  {
    id: '23459090',
    name: "CN7 W/W SIDE MLD'G RH",
    partNumber: 'CN7-20230908T143524',
    productionTime: '2023-09-08 / 14:26:43',
    co2PerUnit: 0.88,
    totalCo2: 19.50,
    lastUpdate: '2022.12.31',
    status: 'YES',
    // Hyundai Elantra (CN7) White
    imageUrl: 'vendor-images/photo-1616422285623-13ff0162193c-w800.jpg' 
  },
  {
    id: '23458872',
    name: "LX2 W/S SIDE MLD'G LH(RHD)",
    partNumber: 'LX2-20230305T091102',
    productionTime: '2023-03-05 / 09:11:02',
    co2PerUnit: 0.84,
    totalCo2: 18.20,
    lastUpdate: '2023.03.05',
    status: 'DONE',
    // Hyundai SUV (Representing Palisade/Tuscon class)
    imageUrl: 'vendor-images/photo-1621929747188-0b4dc28498d2-w800.jpg'
  },
  {
    id: '23459081',
    name: "BC3 W/S SIDE MLD'G LH",
    partNumber: 'BC3-20220731T112000',
    productionTime: '2022-07-31 / 11:20:00',
    co2PerUnit: 0.91,
    totalCo2: 20.10,
    lastUpdate: '2022.07.31',
    status: 'DONE',
    // Hyundai/Kia Hatchback style
    imageUrl: 'vendor-images/photo-1609521263047-f8f205293f24-w800.jpg'
  }
];

export const MOCK_DPP_INSPECTIONS: DPPInspection[] = [
  {
    id: 'insp_001',
    // Synced with the CN7 product image
    imageUrl: 'vendor-images/photo-1616422285623-13ff0162193c-w800.jpg',
    timestamp: '2023-09-08 14:26:43',
    result: 'OK',
    defects: []
  }
];

export const MOCK_DATA_TRANSACTIONS: DataTransaction[] = [
  { no: 4, processId: 'Payment for renewed data received. (300 USD for 500,000 calls)', date: '2023.08.31' },
  { no: 3, processId: 'CO2EQ aggregation completed and transferred.', date: '2023.08.24' },
  { no: 2, processId: 'CO2EQ aggregation started by HANGUK MOLD.', date: '2023.08.22' },
  { no: 1, processId: 'CO2EQ requested by Hyundai.', date: '2023.08.08' },
];

// --- EXISTING ASSETS ---

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'recipe_ai',
    title: 'Recipe.AI',
    provider: 'Korea',
    type: AssetType.AI_MODEL,
    industry: Industry.MANUFACTURING,
    aiCategory: AICategory.SUPPLY_CHAIN,
    description: '생산조건최적화서비스. Manufacturing big data analysis for optimal production conditions.',
    descriptionKo: '제조 빅데이터를 분석해 최적의 생산 조건을 찾아주는 생산조건 최적화 서비스입니다.',
    price: 8500,
    currency: 'USD/mo',
    rating: 4.9,
    reviewCount: 85,
    imageUrl: 'vendor-images/photo-1581091226825-a6a2a5aee158-w600.jpg',
    tags: ['Optimization', 'Recipe', 'Process'],
    certified: true
  },
  {
    id: 'quality_ai',
    title: 'Quality.AI',
    provider: 'Korea',
    type: AssetType.AI_MODEL,
    industry: Industry.ELECTRONICS,
    aiCategory: AICategory.QUALITY_INSPECTION,
    description: '품질예측서비스. AI-driven quality prediction to reduce defect rates.',
    descriptionKo: '불량률을 낮추기 위해 품질을 사전에 예측하는 AI 품질예측 서비스입니다.',
    price: 12000,
    currency: 'USD/mo',
    rating: 4.6,
    reviewCount: 45,
    imageUrl: 'vendor-images/photo-1518770660439-4636190af475-w600.jpg',
    tags: ['Quality', 'Prediction', 'Zero Defect'],
    certified: true
  },
  {
    id: 'inspection_ai',
    title: 'Inspection.AI',
    provider: 'Korea',
    type: AssetType.AI_MODEL,
    industry: Industry.AUTOMOTIVE,
    aiCategory: AICategory.QUALITY_INSPECTION,
    description: '품질검사서비스. Vision-based automated inspection system.',
    descriptionKo: '비전 기반으로 검사 공정을 자동화하는 품질검사 서비스입니다.',
    price: 5000,
    currency: 'USD/mo',
    rating: 4.8,
    reviewCount: 120,
    imageUrl: 'vendor-images/photo-1537462715879-360eeb61a0ad-w600.jpg',
    dataPoints: 15000000,
    tags: ['Vision', 'Inspection', 'Automated'],
    certified: true
  },
  {
    id: 'korea_dt',
    title: 'Korea.DT',
    provider: 'Korea',
    type: AssetType.DIGITAL_TWIN,
    industry: Industry.MANUFACTURING,
    aiCategory: AICategory.DIGITAL_TWIN,
    description: '가상공장서비스. Digital Twin service for virtual factory management.',
    descriptionKo: '가상 공장을 구축해 설비와 공정을 관리하는 디지털 트윈 서비스입니다.',
    price: 15000,
    currency: 'USD/yr',
    rating: 4.7,
    reviewCount: 42,
    imageUrl: 'vendor-images/photo-1563986768609-322da13575f3-w600.jpg',
    tags: ['Digital Twin', 'Virtual Factory', 'Simulation'],
    certified: true
  },
  {
    id: 'netzero_ai',
    title: 'NetZero.AI',
    provider: 'EcoSmart Grid',
    type: AssetType.APP,
    industry: Industry.ENERGY,
    aiCategory: AICategory.ENERGY_OPTIMIZATION,
    description: '에너지최적화서비스. Carbon footprint tracking and energy optimization.',
    descriptionKo: '탄소 배출량을 추적하고 에너지 사용을 최적화하는 서비스입니다.',
    price: 2200,
    currency: 'USD/mo',
    rating: 4.8,
    reviewCount: 156,
    imageUrl: 'vendor-images/photo-1466611653911-95081537e5b7-w600.jpg',
    tags: ['Carbon Reduction', 'Energy Efficiency', 'ESG'],
    certified: true
  },
  {
    id: 'preprocessing_platform',
    title: 'Data Preprocessing Platform',
    provider: 'Korea',
    type: AssetType.APP,
    industry: Industry.MANUFACTURING,
    aiCategory: AICategory.DIGITAL_TWIN,
    description: '데이터 전처리 자동화 플랫폼. Automated preprocessing & MLOps platform.',
    descriptionKo: '데이터 전처리부터 MLOps까지 자동화하는 플랫폼입니다.',
    price: 45000,
    currency: 'USD/yr',
    rating: 5.0,
    reviewCount: 12,
    imageUrl: 'vendor-images/photo-1551288049-bebda4e38f71-w600.jpg',
    tags: ['Preprocessing', 'MLOps', 'Automation', 'Data Ops'],
    certified: true
  },
  {
    id: 'scm_ai',
    title: 'SCM.AI',
    provider: 'Korea',
    type: AssetType.AI_MODEL,
    industry: Industry.LOGISTICS,
    aiCategory: AICategory.SUPPLY_CHAIN,
    description: '공급망 최적화/수요관리. AI-based SCM optimization and demand forecasting.',
    descriptionKo: 'AI 기반 공급망 최적화와 수요 예측을 제공합니다.',
    price: 9000,
    currency: 'USD/mo',
    rating: 4.7,
    reviewCount: 34,
    imageUrl: 'vendor-images/photo-1586528116311-ad8dd3c8310d-w600.jpg',
    tags: ['SCM', 'Demand', 'Logistics'],
    certified: true
  },
  {
    id: 'data_batt_cycle',
    title: 'EV Battery Cycle Data (10k hrs)',
    titleKo: '전기차 배터리 충방전 데이터 (1만 시간)',
    provider: 'LG Energy Solution',
    type: AssetType.DATASET,
    industry: Industry.ENERGY,
    description: 'Comprehensive charge/discharge cycle logs for NCM 811 batteries under various temperature conditions.',
    descriptionKo: '다양한 온도 조건에서 측정한 NCM 811 배터리의 충·방전 사이클 전체 로그입니다.',
    price: 5000,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 120,
    imageUrl: 'vendor-images/photo-1620288627223-53302f4e8c74-w600.jpg',
    dataPoints: 10000000,
    tags: ['Battery', 'EV', 'Energy Storage'],
    certified: true
  },
  {
    id: 'data_steel_tensile',
    title: 'High-Strength Steel Tensile Logs',
    titleKo: '고장력 강판 인장시험 로그',
    provider: 'POSCO',
    type: AssetType.DATASET,
    industry: Industry.MANUFACTURING,
    description: 'Raw tensile strength test results for automotive-grade AHSS steel produced in 2023.',
    descriptionKo: '2023년 생산된 차량용 AHSS 강재의 인장강도 시험 원본 데이터입니다.',
    price: 3500,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 45,
    imageUrl: 'vendor-images/photo-1504917595217-d4dc5ebe6122-w600.jpg',
    dataPoints: 500000,
    tags: ['Steel', 'Material Science', 'Quality'],
    certified: true
  },
  {
    id: 'data_lidar_seoul',
    title: 'Urban Autonomous Driving LIDAR',
    titleKo: '도심 자율주행 라이다 데이터',
    provider: 'Hyundai Motor',
    type: AssetType.DATASET,
    industry: Industry.AUTOMOTIVE,
    description: 'LIDAR point cloud data collected in Gangnam, Seoul during rush hour traffic.',
    descriptionKo: '출퇴근 혼잡 시간대 서울 강남 일대에서 수집한 라이다 포인트 클라우드입니다.',
    price: 15000,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 210,
    imageUrl: 'vendor-images/photo-1449965408869-eaa3f722e40d-w600.jpg',
    dataPoints: 200000000,
    tags: ['Autonomous', 'LIDAR', 'Mobility'],
    certified: true
  },
  {
    id: 'data_wafer_img',
    title: '3nm Wafer Defect Microscopy',
    titleKo: '3nm 웨이퍼 결함 현미경 이미지',
    provider: 'Samsung Electronics',
    type: AssetType.DATASET,
    industry: Industry.ELECTRONICS,
    description: 'High-resolution SEM images of wafer defects categorized by 12 distinct failure modes.',
    descriptionKo: '12가지 결함 유형으로 분류한 고해상도 웨이퍼 SEM 이미지입니다.',
    price: 25000,
    currency: 'USD',
    rating: 5.0,
    reviewCount: 89,
    imageUrl: 'vendor-images/photo-1555664424-778a1e5e1b48-w600.jpg',
    dataPoints: 50000,
    tags: ['Semiconductor', 'Vision', 'Defect'],
    certified: true
  },
  {
    id: 'data_logistics_apac',
    title: 'APAC Shipping Manifests 2023',
    titleKo: '아시아·태평양 선적 매니페스트 2023',
    provider: 'HMM',
    type: AssetType.DATASET,
    industry: Industry.LOGISTICS,
    description: 'Anonymized shipping manifests and route efficiency data for Trans-Pacific routes.',
    descriptionKo: '환태평양 항로의 익명화된 선적 명세와 경로 효율 데이터입니다.',
    price: 4200,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 32,
    imageUrl: 'vendor-images/photo-1578575437130-527eed3abbec-w600.jpg',
    dataPoints: 1200000,
    tags: ['Logistics', 'Shipping', 'Supply Chain'],
    certified: false
  },
  {
    id: 'data_chemical_rxn',
    title: 'Polymer Synthesis Reaction Logs',
    titleKo: '고분자 합성 반응 로그',
    provider: 'LG Chem',
    type: AssetType.DATASET,
    industry: Industry.MANUFACTURING,
    description: 'Time-series sensor data (Temp, Pressure, Catalyst) for ABS plastic synthesis.',
    descriptionKo: 'ABS 플라스틱 합성 공정의 온도·압력·촉매 시계열 센서 데이터입니다.',
    price: 8000,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 15,
    imageUrl: 'vendor-images/photo-1532094349884-543bc11b234d-w600.jpg',
    dataPoints: 3000000,
    tags: ['Chemical', 'R&D', 'Process Data'],
    certified: true
  },
  {
    id: 'data_solar_eff',
    title: 'Solar Module Efficiency (Weather)',
    titleKo: '태양광 모듈 발전효율 (기상 연계)',
    provider: 'Hanwha Solutions',
    type: AssetType.DATASET,
    industry: Industry.ENERGY,
    description: 'Correlation data between weather conditions and PV module output efficiency.',
    descriptionKo: '기상 조건과 태양광 모듈 출력 효율의 상관관계 데이터입니다.',
    price: 1200,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 60,
    imageUrl: 'vendor-images/photo-1508514177221-188b1cf16e9d-w600.jpg',
    dataPoints: 80000,
    tags: ['Solar', 'Renewable', 'Weather'],
    certified: true
  },
  {
    id: 'eq_robot_arm_x1',
    title: '6-Axis Industrial Robot X1',
    titleKo: '6축 산업용 로봇 X1',
    provider: 'RoboTech Solutions',
    type: AssetType.EQUIPMENT,
    industry: Industry.MANUFACTURING,
    description: 'High-precision 6-axis welding robot arm. Payload 10kg.',
    descriptionKo: '가반하중 10kg의 고정밀 6축 용접 로봇 암입니다.',
    price: 25000,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 12,
    imageUrl: 'vendor-images/photo-1531746790731-6c087fecd65a-w600.jpg',
    tags: ['Robot', 'Hardware', 'Automation'],
    certified: true
  },
  {
    id: 'eq_cnc_5axis',
    title: 'PUMA 5-Axis Turning Center',
    titleKo: 'PUMA 5축 터닝 센터',
    provider: 'DN Solutions',
    type: AssetType.EQUIPMENT,
    industry: Industry.MANUFACTURING,
    description: 'High-performance 5-axis CNC machine for complex aerospace parts.',
    descriptionKo: '복잡한 항공우주 부품 가공을 위한 고성능 5축 CNC 장비입니다.',
    price: 180000,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 8,
    imageUrl: 'vendor-images/photo-1526628953301-3e589a6a8b74-w600.jpg',
    tags: ['CNC', 'Machining', 'Heavy Equip'],
    certified: true
  },
  {
    id: 'eq_agv_heavy',
    title: 'Heavy Duty AGV (1000kg)',
    titleKo: '중량물 AGV (1,000kg)',
    provider: 'Hyundai Robotics',
    type: AssetType.EQUIPMENT,
    industry: Industry.LOGISTICS,
    description: 'Automated Guided Vehicle for pallet transport. Lidar navigation included.',
    descriptionKo: '팔레트 운반용 무인 반송차로, 라이다 자율주행이 포함되어 있습니다.',
    price: 45000,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 22,
    imageUrl: 'vendor-images/photo-1586528116311-ad8dd3c8310d-w600.jpg',
    tags: ['AGV', 'Logistics', 'Automation'],
    certified: true
  },
  {
    id: 'eq_3d_printer',
    title: 'Industrial Metal 3D Printer',
    titleKo: '산업용 금속 3D 프린터',
    provider: 'InssTek',
    type: AssetType.EQUIPMENT,
    industry: Industry.MANUFACTURING,
    description: 'DED (Directed Energy Deposition) metal printer for parts repair and manufacturing.',
    descriptionKo: '부품 보수와 제작에 쓰이는 DED(직접 에너지 적층) 방식 금속 프린터입니다.',
    price: 210000,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 5,
    imageUrl: 'vendor-images/photo-1631541909061-71e349d1f203-w600.jpg',
    tags: ['3D Print', 'Additive', 'Metal'],
    certified: false
  },
  {
    id: 'eq_press_500t',
    title: '500 Ton Hydraulic Press',
    titleKo: '500톤 유압 프레스',
    provider: 'Hyundai WIA',
    type: AssetType.EQUIPMENT,
    industry: Industry.MANUFACTURING,
    description: 'Automated hydraulic press for automotive body panel stamping.',
    descriptionKo: '차체 패널 스탬핑용 자동화 유압 프레스입니다.',
    price: 320000,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 15,
    imageUrl: 'vendor-images/photo-1504917595217-d4dc5ebe6122-w600.jpg',
    tags: ['Press', 'Stamping', 'Heavy Machinery'],
    certified: true
  },
  {
    id: 'eq_smd_mounter',
    title: 'High-Speed Chip Mounter',
    titleKo: '고속 칩 마운터',
    provider: 'Hanwha Precision',
    type: AssetType.EQUIPMENT,
    industry: Industry.ELECTRONICS,
    description: 'SMT pick-and-place machine with 45,000 CPH speed.',
    descriptionKo: '시간당 45,000개를 처리하는 SMT 표면실장 장비입니다.',
    price: 95000,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 30,
    imageUrl: 'vendor-images/photo-1597852074816-d933c7d2b988-w600.jpg',
    tags: ['SMT', 'Electronics', 'Assembly'],
    certified: true
  },
  {
    id: 'eq_drone_inspect',
    title: 'Thermal Inspection Drone',
    titleKo: '열화상 점검 드론',
    provider: 'Doosan Mobility',
    type: AssetType.EQUIPMENT,
    industry: Industry.ENERGY,
    description: 'Hydrogen fuel cell drone for long-endurance pipeline and power line inspection.',
    descriptionKo: '수소연료전지로 장시간 비행하며 배관과 송전선을 점검하는 드론입니다.',
    price: 35000,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 18,
    imageUrl: 'vendor-images/photo-1473968512647-3e447244af8f-w600.jpg',
    tags: ['Drone', 'Inspection', 'Hydrogen'],
    certified: true
  },
  {
    id: 'part_cnc_ctrl',
    title: 'CNC Controller V2 Module',
    titleKo: 'CNC 컨트롤러 V2 모듈',
    provider: 'Precision Gear',
    type: AssetType.PART,
    industry: Industry.MANUFACTURING,
    description: 'Replacement control module for CNC milling machines.',
    descriptionKo: 'CNC 밀링 장비용 교체 제어 모듈입니다.',
    price: 1200,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 28,
    imageUrl: 'vendor-images/photo-1592659762303-90081d34b277-w600.jpg',
    tags: ['CNC', 'Spare Part', 'Controller'],
    certified: false
  },
  {
    id: 'part_servo_motor',
    title: 'AC Servo Motor 2.5kW',
    titleKo: 'AC 서보모터 2.5kW',
    provider: 'LS Electric',
    type: AssetType.PART,
    industry: Industry.MANUFACTURING,
    description: 'High torque AC servo motor for industrial automation. IP67 rated.',
    descriptionKo: 'IP67 등급의 산업 자동화용 고토크 AC 서보모터입니다.',
    price: 450,
    currency: 'USD',
    rating: 4.8,
    reviewCount: 56,
    imageUrl: 'vendor-images/photo-1581092160562-40aa08e78837-w600.jpg',
    tags: ['Motor', 'Servo', 'Automation'],
    certified: true
  },
  {
    id: 'part_iot_gateway',
    title: 'Industrial Edge IoT Gateway',
    titleKo: '산업용 엣지 IoT 게이트웨이',
    provider: 'Advantech',
    type: AssetType.PART,
    industry: Industry.ELECTRONICS,
    description: '5G-ready IoT gateway for connecting legacy PLC to DataSpace.',
    descriptionKo: '기존 PLC를 데이터스페이스에 연결하는 5G 지원 IoT 게이트웨이입니다.',
    price: 850,
    currency: 'USD',
    rating: 4.6,
    reviewCount: 42,
    imageUrl: 'vendor-images/photo-1558346490-a72e53ae2d4f-w600.jpg',
    tags: ['IoT', 'Gateway', 'Connectivity'],
    certified: true
  },
  {
    id: 'part_robot_gripper',
    title: 'Pneumatic Parallel Gripper',
    titleKo: '공압 평행 그리퍼',
    provider: 'Schunk',
    type: AssetType.PART,
    industry: Industry.MANUFACTURING,
    description: '2-finger parallel gripper for robot arms. Stroke 20mm.',
    descriptionKo: '스트로크 20mm의 로봇 암용 2지 평행 그리퍼입니다.',
    price: 320,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 19,
    imageUrl: 'vendor-images/photo-1530893609608-32a9af3aa95c-w600.jpg',
    tags: ['Gripper', 'Robot', 'End Effector'],
    certified: true
  },
  {
    id: 'part_hmi_panel',
    title: '15-inch Touch HMI Panel',
    titleKo: '15인치 터치 HMI 패널',
    provider: 'Siemens',
    type: AssetType.PART,
    industry: Industry.MANUFACTURING,
    description: 'Rugged touch screen interface for factory machinery control.',
    descriptionKo: '공장 설비 제어용 러기드 터치스크린 인터페이스입니다.',
    price: 1100,
    currency: 'USD',
    rating: 4.5,
    reviewCount: 33,
    imageUrl: 'vendor-images/photo-1526628953301-3e589a6a8b74-w600.jpg',
    tags: ['HMI', 'Display', 'Control'],
    certified: true
  },
  {
    id: 'part_ball_screw',
    title: 'Precision Ball Screw 50mm',
    titleKo: '정밀 볼스크류 50mm',
    provider: 'NSK',
    type: AssetType.PART,
    industry: Industry.MANUFACTURING,
    description: 'High-load capacity ball screw for linear motion systems.',
    descriptionKo: '직선 운동 시스템용 고하중 볼스크류입니다.',
    price: 280,
    currency: 'USD',
    rating: 4.9,
    reviewCount: 14,
    imageUrl: 'vendor-images/photo-1616423640778-28d1b53229bd-w600.jpg',
    tags: ['Linear Motion', 'Hardware', 'Mechanical'],
    certified: true
  },
  {
    id: 'part_hydraulic_pump',
    title: 'Axial Piston Pump V3',
    titleKo: '가변 사판식 피스톤 펌프 V3',
    provider: 'Bosch Rexroth',
    type: AssetType.PART,
    industry: Industry.MANUFACTURING,
    description: 'Variable displacement axial piston pump for hydraulic systems.',
    descriptionKo: '유압 시스템용 가변 용량 액시얼 피스톤 펌프입니다.',
    price: 1800,
    currency: 'USD',
    rating: 4.7,
    reviewCount: 25,
    imageUrl: 'vendor-images/photo-1581092580497-e0d23cbdf1dc-w600.jpg',
    tags: ['Hydraulic', 'Pump', 'Fluid Power'],
    certified: true
  }
];

export const MOCK_COMPANIES: Company[] = [
  { 
      id: 'c_1', 
      name: 'Hyundai Motor', 
      description: 'Global Automotive Leader',
      descriptionKo: '글로벌 완성차 기업', 
      industry: Industry.AUTOMOTIVE, 
      productsCount: 124, 
      logo: 'H',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Hyundai_Motor_Company_logo.svg/800px-Hyundai_Motor_Company_logo.svg.png'
  },
  { 
      id: 'c_2', 
      name: 'Samsung Electronics', 
      description: 'Semiconductor & Consumer Electronics',
      descriptionKo: '반도체·가전 전문 기업', 
      industry: Industry.ELECTRONICS, 
      productsCount: 340, 
      logo: 'S',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Samsung_Logo.svg/1280px-Samsung_Logo.svg.png'
  },
  { 
      id: 'c_3', 
      name: 'LG Electronics', 
      description: 'Smart Home & Appliances',
      descriptionKo: '스마트홈·생활가전 기업', 
      industry: Industry.ELECTRONICS, 
      productsCount: 210, 
      logo: 'L',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/LG_logo_%282015%29.svg/1200px-LG_logo_%282015%29.svg.png'
  },
  { 
      id: 'c_4', 
      name: 'Doosan Robotics', 
      description: 'Collaborative Robots',
      descriptionKo: '협동로봇 전문 기업', 
      industry: Industry.MANUFACTURING, 
      productsCount: 45, 
      logo: 'D',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Doosan_logo.svg/1200px-Doosan_logo.svg.png'
  },
  { 
      id: 'c_5', 
      name: 'POSCO', 
      description: 'Steel & Materials',
      descriptionKo: '철강·소재 기업', 
      industry: Industry.MANUFACTURING, 
      productsCount: 89, 
      logo: 'P',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Posco-logo.svg/1200px-Posco-logo.svg.png'
  },
];

export const RECENT_TRANSACTIONS = [
  { id: 'tx_998', asset: 'Recipe.AI License', amount: 8500, date: '2024-05-20', status: 'Confirmed' },
  { id: 'tx_999', asset: 'Inspection.AI Setup', amount: 5000, date: '2024-05-21', status: 'Confirmed' },
];
