/**
 * Directory of the organisations that appear in the ecosystem map.
 *
 * Korean members carry a full profile; partners outside Korea carry a sector so
 * the filters still work on every node. Sector, headquarters and founding year
 * are matters of public record. The dataspace fields - the role each plays and
 * how many assets it publishes - are part of this demo, like the rest of the
 * platform's traffic figures.
 */

export type Sector =
  | 'Semiconductor'
  | 'Automotive'
  | 'Battery'
  | 'Materials'
  | 'Chemicals'
  | 'HeavyIndustry'
  | 'Energy'
  | 'Electronics'
  | 'ICT'
  | 'Logistics'
  | 'Aerospace'
  | 'Robotics'
  | 'Bio'
  | 'Construction'
  | 'Research'
  | 'PublicAgency'
  | 'Academia';

export interface DirectoryEntry {
  name: string;
  nameKo?: string;
  kind: 'Enterprise' | 'Institute' | 'Agency' | 'Academia';
  sector: Sector;
  hq?: string;
  hqKo?: string;
  founded?: string;
  summary?: string;
  summaryKo?: string;
  role?: string;
  roleKo?: string;
}

export const SECTOR_LABELS: Record<Sector, { en: string; ko: string }> = {
  Semiconductor: { en: 'Semiconductor', ko: '반도체' },
  Automotive: { en: 'Automotive', ko: '자동차' },
  Battery: { en: 'Battery', ko: '배터리' },
  Materials: { en: 'Steel & Materials', ko: '소재·철강' },
  Chemicals: { en: 'Chemicals', ko: '화학' },
  HeavyIndustry: { en: 'Shipbuilding & Heavy', ko: '조선·중공업' },
  Energy: { en: 'Energy', ko: '에너지' },
  Electronics: { en: 'Electronics', ko: '전자' },
  ICT: { en: 'ICT & Platform', ko: 'ICT·플랫폼' },
  Logistics: { en: 'Logistics', ko: '물류' },
  Aerospace: { en: 'Aerospace & Defence', ko: '항공우주·방산' },
  Robotics: { en: 'Machinery & Robotics', ko: '기계·로보틱스' },
  Bio: { en: 'Bio & Healthcare', ko: '바이오' },
  Construction: { en: 'Construction', ko: '건설' },
  Research: { en: 'Research Institute', ko: '연구기관' },
  PublicAgency: { en: 'Public Agency', ko: '공공기관' },
  Academia: { en: 'University', ko: '대학' },
};

export const DIRECTORY: DirectoryEntry[] = [
  { name: 'Samsung Electronics', nameKo: '삼성전자', kind: 'Enterprise', sector: 'Semiconductor',
    hq: 'Suwon', hqKo: '경기 수원', founded: '1969',
    summary: 'Memory, foundry and consumer electronics.', summaryKo: '메모리·파운드리·가전을 아우르는 종합 전자기업입니다.',
    role: 'Publishes wafer and yield datasets.', roleKo: '웨이퍼·수율 데이터를 제공합니다.' },
  { name: 'SK hynix', nameKo: 'SK하이닉스', kind: 'Enterprise', sector: 'Semiconductor',
    hq: 'Icheon', hqKo: '경기 이천', founded: '1983',
    summary: 'DRAM and NAND memory manufacturer.', summaryKo: 'DRAM·낸드 메모리를 생산합니다.',
    role: 'Publishes fab process telemetry.', roleKo: '팹 공정 텔레메트리를 제공합니다.' },
  { name: 'SK Siltron', nameKo: 'SK실트론', kind: 'Enterprise', sector: 'Semiconductor',
    hq: 'Gumi', hqKo: '경북 구미', founded: '1983',
    summary: 'Silicon and SiC wafer supplier.', summaryKo: '실리콘·SiC 웨이퍼를 공급합니다.',
    role: 'Supplies wafer quality certificates.', roleKo: '웨이퍼 품질 인증서를 공급합니다.' },
  { name: 'Samsung Electronics Gumi', nameKo: '삼성전자 구미', kind: 'Enterprise', sector: 'Electronics',
    hq: 'Gumi', hqKo: '경북 구미', founded: '1980',
    summary: 'Mobile and network equipment plant.', summaryKo: '모바일·네트워크 장비 생산 사업장입니다.',
    role: 'Shares line-level quality data.', roleKo: '라인 단위 품질 데이터를 공유합니다.' },
  { name: 'Hyundai Motor', nameKo: '현대자동차', kind: 'Enterprise', sector: 'Automotive',
    hq: 'Seoul', hqKo: '서울', founded: '1967',
    summary: 'Korea\'s largest automaker.', summaryKo: '국내 최대 완성차 기업입니다.',
    role: 'Anchors the automotive chain as OEM.', roleKo: 'OEM으로서 자동차 체인의 기준점입니다.' },
  { name: 'Hyundai Motor Ulsan', nameKo: '현대자동차 울산공장', kind: 'Enterprise', sector: 'Automotive',
    hq: 'Ulsan', hqKo: '울산', founded: '1968',
    summary: 'The world\'s largest single auto plant.', summaryKo: '단일 규모 세계 최대 자동차 공장입니다.',
    role: 'Publishes assembly line PCF.', roleKo: '조립 라인 PCF를 제공합니다.' },
  { name: 'Kia', nameKo: '기아', kind: 'Enterprise', sector: 'Automotive',
    hq: 'Seoul', hqKo: '서울', founded: '1944',
    summary: 'Automaker within Hyundai Motor Group.', summaryKo: '현대자동차그룹의 완성차 기업입니다.',
    role: 'Shares EV production data.', roleKo: '전기차 생산 데이터를 공유합니다.' },
  { name: 'Hyundai Mobis', nameKo: '현대모비스', kind: 'Enterprise', sector: 'Automotive',
    hq: 'Seoul', hqKo: '서울', founded: '1977',
    summary: 'Chassis, cockpit and module supplier.', summaryKo: '섀시·칵핏·모듈을 공급합니다.',
    role: 'Tier 1 module traceability.', roleKo: 'Tier 1 모듈 이력을 제공합니다.' },
  { name: 'HL Mando', nameKo: 'HL만도', kind: 'Enterprise', sector: 'Automotive',
    hq: 'Pyeongtaek', hqKo: '경기 평택', founded: '1962',
    summary: 'Brake, steering and suspension systems.', summaryKo: '제동·조향·현가 시스템을 공급합니다.',
    role: 'Shares chassis component records.', roleKo: '섀시 부품 이력을 공유합니다.' },
  { name: 'Hyundai WIA', nameKo: '현대위아', kind: 'Enterprise', sector: 'Automotive',
    hq: 'Changwon', hqKo: '경남 창원', founded: '1976',
    summary: 'Engine parts and machine tools.', summaryKo: '엔진 부품과 공작기계를 생산합니다.',
    role: 'Publishes machining process data.', roleKo: '가공 공정 데이터를 제공합니다.' },
  { name: 'Hyundai Transys', nameKo: '현대트랜시스', kind: 'Enterprise', sector: 'Automotive',
    hq: 'Seosan', hqKo: '충남 서산', founded: '2019',
    summary: 'Transmissions and vehicle seats.', summaryKo: '변속기와 시트를 생산합니다.',
    role: 'Shares powertrain test logs.', roleKo: '파워트레인 시험 로그를 공유합니다.' },
  { name: 'SL Corporation', nameKo: '에스엘', kind: 'Enterprise', sector: 'Automotive',
    hq: 'Daegu', hqKo: '대구', founded: '1954',
    summary: 'Automotive lamps and chassis parts.', summaryKo: '자동차 램프·섀시 부품을 생산합니다.',
    role: 'Shares lamp module PCF.', roleKo: '램프 모듈 PCF를 공유합니다.' },
  { name: 'PHC', nameKo: '평화정공', kind: 'Enterprise', sector: 'Automotive',
    hq: 'Daegu', hqKo: '대구', founded: '1985',
    summary: 'Door latches and hinge systems.', summaryKo: '도어 래치·힌지 시스템을 생산합니다.',
    role: 'Publishes part-level carbon data.', roleKo: '부품 단위 탄소 데이터를 제공합니다.' },
  { name: 'Iljin', nameKo: '일진', kind: 'Enterprise', sector: 'Automotive',
    hq: 'Seoul', hqKo: '서울', founded: '1968',
    summary: 'Wheel bearings and materials group.', summaryKo: '휠 베어링·소재 사업을 영위합니다.',
    role: 'Shares bearing durability data.', roleKo: '베어링 내구 데이터를 공유합니다.' },
  { name: 'Daedong', nameKo: '대동', kind: 'Enterprise', sector: 'Robotics',
    hq: 'Daegu', hqKo: '대구', founded: '1947',
    summary: 'Agricultural machinery and robotics.', summaryKo: '농기계·로보틱스 기업입니다.',
    role: 'Publishes field machinery telemetry.', roleKo: '농기계 텔레메트리를 제공합니다.' },
  { name: 'LG Energy Solution', nameKo: 'LG에너지솔루션', kind: 'Enterprise', sector: 'Battery',
    hq: 'Seoul', hqKo: '서울', founded: '2020',
    summary: 'EV battery cell manufacturer.', summaryKo: '전기차 배터리 셀을 생산합니다.',
    role: 'Publishes battery passports and PCF.', roleKo: '배터리 여권과 PCF를 제공합니다.' },
  { name: 'Samsung SDI', nameKo: '삼성SDI', kind: 'Enterprise', sector: 'Battery',
    hq: 'Yongin', hqKo: '경기 용인', founded: '1970',
    summary: 'Battery cells and electronic materials.', summaryKo: '배터리 셀과 전자재료를 생산합니다.',
    role: 'Shares cell test datasets.', roleKo: '셀 시험 데이터를 공유합니다.' },
  { name: 'SK On', nameKo: 'SK온', kind: 'Enterprise', sector: 'Battery',
    hq: 'Seoul', hqKo: '서울', founded: '2021',
    summary: 'EV battery maker in the SK group.', summaryKo: 'SK그룹의 전기차 배터리 기업입니다.',
    role: 'Shares cycle-life datasets.', roleKo: '수명 사이클 데이터를 공유합니다.' },
  { name: 'EcoPro BM', nameKo: '에코프로비엠', kind: 'Enterprise', sector: 'Battery',
    hq: 'Cheongju', hqKo: '충북 청주', founded: '2016',
    summary: 'Cathode material producer.', summaryKo: '양극재를 생산합니다.',
    role: 'Publishes cathode traceability.', roleKo: '양극재 이력을 제공합니다.' },
  { name: 'POSCO', nameKo: '포스코', kind: 'Enterprise', sector: 'Materials',
    hq: 'Pohang', hqKo: '경북 포항', founded: '1968',
    summary: 'Integrated steel producer.', summaryKo: '일관제철 기업입니다.',
    role: 'Publishes steel PCF and mill certs.', roleKo: '철강 PCF와 밀시트를 제공합니다.' },
  { name: 'POSCO Future M', nameKo: '포스코퓨처엠', kind: 'Enterprise', sector: 'Battery',
    hq: 'Pohang', hqKo: '경북 포항', founded: '1971',
    summary: 'Anode and cathode materials.', summaryKo: '음극재·양극재를 생산합니다.',
    role: 'Shares material origin records.', roleKo: '소재 원산지 이력을 공유합니다.' },
  { name: 'Hyundai Steel', nameKo: '현대제철', kind: 'Enterprise', sector: 'Materials',
    hq: 'Incheon', hqKo: '인천', founded: '1953',
    summary: 'Automotive steel sheet producer.', summaryKo: '자동차용 강판을 생산합니다.',
    role: 'Shares steel grade certificates.', roleKo: '강종 인증서를 공유합니다.' },
  { name: 'Korea Zinc', nameKo: '고려아연', kind: 'Enterprise', sector: 'Materials',
    hq: 'Seoul', hqKo: '서울', founded: '1974',
    summary: 'Non-ferrous metal smelter.', summaryKo: '비철금속 제련 기업입니다.',
    role: 'Publishes smelting emissions data.', roleKo: '제련 배출 데이터를 제공합니다.' },
  { name: 'Toray Advanced Materials', nameKo: '도레이첨단소재', kind: 'Enterprise', sector: 'Materials',
    hq: 'Gumi', hqKo: '경북 구미', founded: '1999',
    summary: 'Films, fibres and composite materials.', summaryKo: '필름·섬유·복합소재를 생산합니다.',
    role: 'Shares composite spec sheets.', roleKo: '복합소재 사양서를 공유합니다.' },
  { name: 'LG Chem', nameKo: 'LG화학', kind: 'Enterprise', sector: 'Chemicals',
    hq: 'Seoul', hqKo: '서울', founded: '1947',
    summary: 'Petrochemicals and advanced materials.', summaryKo: '석유화학·첨단소재 기업입니다.',
    role: 'Publishes resin batch records.', roleKo: '수지 배치 이력을 제공합니다.' },
  { name: 'Lotte Chemical', nameKo: '롯데케미칼', kind: 'Enterprise', sector: 'Chemicals',
    hq: 'Seoul', hqKo: '서울', founded: '1976',
    summary: 'Basic petrochemical producer.', summaryKo: '기초 석유화학 기업입니다.',
    role: 'Shares reaction process logs.', roleKo: '반응 공정 로그를 공유합니다.' },
  { name: 'Hanwha Solutions', nameKo: '한화솔루션', kind: 'Enterprise', sector: 'Chemicals',
    hq: 'Seoul', hqKo: '서울', founded: '2020',
    summary: 'Chemicals and solar energy.', summaryKo: '화학·태양광 사업을 영위합니다.',
    role: 'Publishes solar module output data.', roleKo: '태양광 모듈 발전 데이터를 제공합니다.' },
  { name: 'Kumho Petrochemical', nameKo: '금호석유화학', kind: 'Enterprise', sector: 'Chemicals',
    hq: 'Seoul', hqKo: '서울', founded: '1970',
    summary: 'Synthetic rubber and resins.', summaryKo: '합성고무·수지를 생산합니다.',
    role: 'Shares rubber compound data.', roleKo: '고무 배합 데이터를 공유합니다.' },
  { name: 'HD Hyundai Heavy Industries', nameKo: 'HD현대중공업', kind: 'Enterprise', sector: 'HeavyIndustry',
    hq: 'Ulsan', hqKo: '울산', founded: '1972',
    summary: 'Shipbuilding and offshore plant.', summaryKo: '조선·해양플랜트 기업입니다.',
    role: 'Shares hull block build records.', roleKo: '선체 블록 제작 이력을 공유합니다.' },
  { name: 'Hanwha Ocean', nameKo: '한화오션', kind: 'Enterprise', sector: 'HeavyIndustry',
    hq: 'Geoje', hqKo: '경남 거제', founded: '1973',
    summary: 'Shipbuilder and defence systems.', summaryKo: '조선·방산 기업입니다.',
    role: 'Publishes vessel lifecycle data.', roleKo: '선박 생애주기 데이터를 제공합니다.' },
  { name: 'Samsung Heavy Industries', nameKo: '삼성중공업', kind: 'Enterprise', sector: 'HeavyIndustry',
    hq: 'Geoje', hqKo: '경남 거제', founded: '1974',
    summary: 'LNG carrier and offshore builder.', summaryKo: 'LNG선·해양설비를 건조합니다.',
    role: 'Shares welding quality records.', roleKo: '용접 품질 이력을 공유합니다.' },
  { name: 'Doosan Enerbility', nameKo: '두산에너빌리티', kind: 'Enterprise', sector: 'HeavyIndustry',
    hq: 'Changwon', hqKo: '경남 창원', founded: '1962',
    summary: 'Power generation equipment maker.', summaryKo: '발전 설비를 제작합니다.',
    role: 'Publishes turbine condition data.', roleKo: '터빈 상태 데이터를 제공합니다.' },
  { name: 'HD Hyundai Infracore', nameKo: 'HD현대인프라코어', kind: 'Enterprise', sector: 'Robotics',
    hq: 'Incheon', hqKo: '인천', founded: '1937',
    summary: 'Construction equipment and engines.', summaryKo: '건설기계·엔진을 생산합니다.',
    role: 'Shares equipment telemetry.', roleKo: '장비 텔레메트리를 공유합니다.' },
  { name: 'Hyundai Rotem', nameKo: '현대로템', kind: 'Enterprise', sector: 'Aerospace',
    hq: 'Uiwang', hqKo: '경기 의왕', founded: '1977',
    summary: 'Rolling stock and defence vehicles.', summaryKo: '철도차량·방산차량을 생산합니다.',
    role: 'Publishes rolling stock maintenance data.', roleKo: '철도차량 정비 데이터를 제공합니다.' },
  { name: 'Hyosung Heavy Industries', nameKo: '효성중공업', kind: 'Enterprise', sector: 'Energy',
    hq: 'Changwon', hqKo: '경남 창원', founded: '2018',
    summary: 'Power transmission equipment.', summaryKo: '전력 송배전 설비를 생산합니다.',
    role: 'Shares grid equipment data.', roleKo: '전력설비 데이터를 공유합니다.' },
  { name: 'Doosan Robotics', nameKo: '두산로보틱스', kind: 'Enterprise', sector: 'Robotics',
    hq: 'Suwon', hqKo: '경기 수원', founded: '2015',
    summary: 'Collaborative robot manufacturer.', summaryKo: '협동로봇을 생산합니다.',
    role: 'Publishes cobot motion datasets.', roleKo: '협동로봇 모션 데이터를 제공합니다.' },
  { name: 'Hyundai Robotics', nameKo: '현대로보틱스', kind: 'Enterprise', sector: 'Robotics',
    hq: 'Daegu', hqKo: '대구', founded: '2020',
    summary: 'Industrial robot manufacturer.', summaryKo: '산업용 로봇을 생산합니다.',
    role: 'Shares robot operation logs.', roleKo: '로봇 가동 로그를 공유합니다.' },
  { name: 'Rainbow Robotics', nameKo: '레인보우로보틱스', kind: 'Enterprise', sector: 'Robotics',
    hq: 'Daejeon', hqKo: '대전', founded: '2011',
    summary: 'Collaborative and humanoid robots.', summaryKo: '협동로봇·휴머노이드를 개발합니다.',
    role: 'Publishes joint torque datasets.', roleKo: '관절 토크 데이터를 제공합니다.' },
  { name: 'LS Electric', nameKo: 'LS일렉트릭', kind: 'Enterprise', sector: 'Energy',
    hq: 'Anyang', hqKo: '경기 안양', founded: '1974',
    summary: 'Power and automation equipment.', summaryKo: '전력·자동화 기기를 생산합니다.',
    role: 'Shares switchgear telemetry.', roleKo: '배전반 텔레메트리를 공유합니다.' },
  { name: 'KEPCO', nameKo: '한국전력공사', kind: 'Agency', sector: 'Energy',
    hq: 'Naju', hqKo: '전남 나주', founded: '1961',
    summary: 'National electric utility.', summaryKo: '국가 전력 공기업입니다.',
    role: 'Provides grid carbon intensity.', roleKo: '계통 탄소집약도를 제공합니다.' },
  { name: 'SK Energy', nameKo: 'SK에너지', kind: 'Enterprise', sector: 'Energy',
    hq: 'Seoul', hqKo: '서울', founded: '1962',
    summary: 'Refining and petroleum products.', summaryKo: '정유·석유제품 기업입니다.',
    role: 'Shares refinery energy data.', roleKo: '정유 에너지 데이터를 공유합니다.' },
  { name: 'S-OIL', nameKo: '에쓰오일', kind: 'Enterprise', sector: 'Energy',
    hq: 'Seoul', hqKo: '서울', founded: '1976',
    summary: 'Refiner and petrochemical producer.', summaryKo: '정유·석유화학 기업입니다.',
    role: 'Publishes fuel lifecycle data.', roleKo: '연료 생애주기 데이터를 제공합니다.' },
  { name: 'GS Caltex', nameKo: 'GS칼텍스', kind: 'Enterprise', sector: 'Energy',
    hq: 'Seoul', hqKo: '서울', founded: '1967',
    summary: 'Refining and lubricants.', summaryKo: '정유·윤활유 기업입니다.',
    role: 'Shares process emissions data.', roleKo: '공정 배출 데이터를 공유합니다.' },
  { name: 'KOGAS', nameKo: '한국가스공사', kind: 'Agency', sector: 'Energy',
    hq: 'Daegu', hqKo: '대구', founded: '1983',
    summary: 'National gas utility.', summaryKo: '국가 가스 공기업입니다.',
    role: 'Provides LNG supply data.', roleKo: 'LNG 공급 데이터를 제공합니다.' },
  { name: 'LG Electronics', nameKo: 'LG전자', kind: 'Enterprise', sector: 'Electronics',
    hq: 'Seoul', hqKo: '서울', founded: '1958',
    summary: 'Home appliances and vehicle components.', summaryKo: '생활가전·전장 부품 기업입니다.',
    role: 'Publishes appliance DPP records.', roleKo: '가전 DPP 이력을 제공합니다.' },
  { name: 'LG Display', nameKo: 'LG디스플레이', kind: 'Enterprise', sector: 'Electronics',
    hq: 'Seoul', hqKo: '서울', founded: '1985',
    summary: 'OLED and LCD panel maker.', summaryKo: 'OLED·LCD 패널을 생산합니다.',
    role: 'Shares panel defect datasets.', roleKo: '패널 결함 데이터를 공유합니다.' },
  { name: 'LG Innotek', nameKo: 'LG이노텍', kind: 'Enterprise', sector: 'Electronics',
    hq: 'Seoul', hqKo: '서울', founded: '1970',
    summary: 'Camera modules and substrates.', summaryKo: '카메라 모듈·기판을 생산합니다.',
    role: 'Publishes module test data.', roleKo: '모듈 시험 데이터를 제공합니다.' },
  { name: 'Samsung Electro-Mechanics', nameKo: '삼성전기', kind: 'Enterprise', sector: 'Electronics',
    hq: 'Suwon', hqKo: '경기 수원', founded: '1973',
    summary: 'MLCC and package substrates.', summaryKo: 'MLCC·패키지 기판을 생산합니다.',
    role: 'Shares component reliability data.', roleKo: '부품 신뢰성 데이터를 공유합니다.' },
  { name: 'Naver', nameKo: '네이버', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '1999',
    summary: 'Search platform and cloud services.', summaryKo: '검색 플랫폼·클라우드 기업입니다.',
    role: 'Operates search and AI services.', roleKo: '검색·AI 서비스를 운영합니다.' },
  { name: 'Naver Cloud', nameKo: '네이버클라우드', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '2009',
    summary: 'Cloud infrastructure provider.', summaryKo: '클라우드 인프라를 제공합니다.',
    role: 'Hosts dataspace connectors.', roleKo: '데이터스페이스 커넥터를 호스팅합니다.' },
  { name: 'Kakao', nameKo: '카카오', kind: 'Enterprise', sector: 'ICT',
    hq: 'Jeju', hqKo: '제주', founded: '1995',
    summary: 'Messaging and internet platform.', summaryKo: '메신저·인터넷 플랫폼 기업입니다.',
    role: 'Provides platform integration.', roleKo: '플랫폼 연동을 제공합니다.' },
  { name: 'Kakao Enterprise', nameKo: '카카오엔터프라이즈', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '2019',
    summary: 'Enterprise AI and cloud services.', summaryKo: '기업용 AI·클라우드 기업입니다.',
    role: 'Supplies AI workbench services.', roleKo: 'AI 워크벤치를 공급합니다.' },
  { name: 'Kakao Mobility', nameKo: '카카오모빌리티', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '2017',
    summary: 'Mobility platform operator.', summaryKo: '모빌리티 플랫폼 기업입니다.',
    role: 'Shares mobility demand data.', roleKo: '모빌리티 수요 데이터를 공유합니다.' },
  { name: 'Samsung SDS', nameKo: '삼성SDS', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seoul', hqKo: '서울', founded: '1985',
    summary: 'IT services and logistics platform.', summaryKo: 'IT 서비스·물류 플랫폼 기업입니다.',
    role: 'Runs supply chain integrations.', roleKo: '공급망 연동을 운영합니다.' },
  { name: 'LG CNS', nameKo: 'LG CNS', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seoul', hqKo: '서울', founded: '1987',
    summary: 'Systems integration and smart factory.', summaryKo: 'SI·스마트팩토리 기업입니다.',
    role: 'Builds factory data pipelines.', roleKo: '공장 데이터 파이프라인을 구축합니다.' },
  { name: 'SK AX', nameKo: 'SK AX', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '1991',
    summary: 'Digital transformation services.', summaryKo: '디지털 전환 서비스 기업입니다.',
    role: 'Delivers AI transformation projects.', roleKo: 'AI 전환 프로젝트를 수행합니다.' },
  { name: 'KT', nameKo: 'KT', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '1981',
    summary: 'Telecom and cloud operator.', summaryKo: '통신·클라우드 사업자입니다.',
    role: 'Provides network and edge nodes.', roleKo: '네트워크·엣지 노드를 제공합니다.' },
  { name: 'SK Telecom', nameKo: 'SK텔레콤', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seoul', hqKo: '서울', founded: '1984',
    summary: 'Mobile network and AI operator.', summaryKo: '이동통신·AI 사업자입니다.',
    role: 'Provides 5G industrial networks.', roleKo: '5G 산업망을 제공합니다.' },
  { name: 'SK Planet', nameKo: 'SK플래닛', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '2011',
    summary: 'Commerce and data platform.', summaryKo: '커머스·데이터 플랫폼 기업입니다.',
    role: 'Shares commerce analytics.', roleKo: '커머스 분석을 공유합니다.' },
  { name: 'AhnLab', nameKo: '안랩', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '1995',
    summary: 'Information security software.', summaryKo: '정보보안 소프트웨어 기업입니다.',
    role: 'Certifies connector security.', roleKo: '커넥터 보안을 인증합니다.' },
  { name: 'Hancom', nameKo: '한글과컴퓨터', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '1990',
    summary: 'Office software and document AI.', summaryKo: '오피스 SW·문서 AI 기업입니다.',
    role: 'Supplies document exchange formats.', roleKo: '문서 교환 포맷을 공급합니다.' },
  { name: 'NCSOFT', nameKo: '엔씨소프트', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '1997',
    summary: 'Game developer and AI research.', summaryKo: '게임 개발·AI 연구 기업입니다.',
    role: 'Contributes simulation compute.', roleKo: '시뮬레이션 연산을 지원합니다.' },
  { name: 'Nexon', nameKo: '넥슨', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '1994',
    summary: 'Online game developer.', summaryKo: '온라인 게임 개발사입니다.',
    role: 'Contributes rendering research.', roleKo: '렌더링 연구를 지원합니다.' },
  { name: 'onepredict', nameKo: '원프레딕트', kind: 'Enterprise', sector: 'Robotics',
    hq: 'Seoul', hqKo: '서울', founded: '2016',
    summary: 'Industrial AI for predictive maintenance.', summaryKo: '설비 예지보전 산업 AI 기업입니다.',
    role: 'Supplies diagnosis models.', roleKo: '고장 진단 모델을 공급합니다.' },
  { name: 'MakinaRocks', nameKo: '마키나락스', kind: 'Enterprise', sector: 'ICT',
    hq: 'Seoul', hqKo: '서울', founded: '2017',
    summary: 'Industrial AI and anomaly detection.', summaryKo: '산업 AI·이상탐지 기업입니다.',
    role: 'Supplies anomaly detection models.', roleKo: '이상탐지 모델을 공급합니다.' },
  { name: 'HMM', nameKo: 'HMM', kind: 'Enterprise', sector: 'Logistics',
    hq: 'Seoul', hqKo: '서울', founded: '1976',
    summary: 'Container shipping line.', summaryKo: '컨테이너 해운 기업입니다.',
    role: 'Publishes shipping manifests.', roleKo: '선적 명세를 제공합니다.' },
  { name: 'CJ Logistics', nameKo: 'CJ대한통운', kind: 'Enterprise', sector: 'Logistics',
    hq: 'Seoul', hqKo: '서울', founded: '1930',
    summary: 'Integrated logistics operator.', summaryKo: '종합 물류 기업입니다.',
    role: 'Shares route efficiency data.', roleKo: '경로 효율 데이터를 공유합니다.' },
  { name: 'Pan Ocean', nameKo: '팬오션', kind: 'Enterprise', sector: 'Logistics',
    hq: 'Seoul', hqKo: '서울', founded: '1966',
    summary: 'Bulk and LNG shipping.', summaryKo: '벌크·LNG 해운 기업입니다.',
    role: 'Shares voyage emissions data.', roleKo: '항해 배출 데이터를 공유합니다.' },
  { name: 'SM Line', nameKo: '에스엠상선', kind: 'Enterprise', sector: 'Logistics',
    hq: 'Seoul', hqKo: '서울', founded: '2016',
    summary: 'Container shipping operator.', summaryKo: '컨테이너 해운 기업입니다.',
    role: 'Publishes container tracking.', roleKo: '컨테이너 추적 정보를 제공합니다.' },
  { name: 'Hanjin Transportation', nameKo: '한진', kind: 'Enterprise', sector: 'Logistics',
    hq: 'Seoul', hqKo: '서울', founded: '1945',
    summary: 'Land, air and port logistics.', summaryKo: '육상·항공·항만 물류 기업입니다.',
    role: 'Shares terminal handling data.', roleKo: '터미널 처리 데이터를 공유합니다.' },
  { name: 'Busan Port Authority', nameKo: '부산항만공사', kind: 'Agency', sector: 'Logistics',
    hq: 'Busan', hqKo: '부산', founded: '2004',
    summary: 'Operator of Busan Port.', summaryKo: '부산항을 운영하는 공기업입니다.',
    role: 'Provides port call records.', roleKo: '항만 입출항 기록을 제공합니다.' },
  { name: 'Korean Air', nameKo: '대한항공', kind: 'Enterprise', sector: 'Aerospace',
    hq: 'Seoul', hqKo: '서울', founded: '1969',
    summary: 'Flag carrier and aerospace division.', summaryKo: '국적 항공사이자 항공우주 사업자입니다.',
    role: 'Shares air cargo capacity data.', roleKo: '항공 화물 정보를 공유합니다.' },
  { name: 'Korea Aerospace Industries', nameKo: '한국항공우주산업', kind: 'Enterprise', sector: 'Aerospace',
    hq: 'Sacheon', hqKo: '경남 사천', founded: '1999',
    summary: 'Aircraft and space systems maker.', summaryKo: '항공기·우주 시스템을 생산합니다.',
    role: 'Publishes airframe part records.', roleKo: '기체 부품 이력을 제공합니다.' },
  { name: 'Hanwha Aerospace', nameKo: '한화에어로스페이스', kind: 'Enterprise', sector: 'Aerospace',
    hq: 'Changwon', hqKo: '경남 창원', founded: '1977',
    summary: 'Aero engines and defence systems.', summaryKo: '항공엔진·방산 시스템 기업입니다.',
    role: 'Shares engine test datasets.', roleKo: '엔진 시험 데이터를 공유합니다.' },
  { name: 'LIG Nex1', nameKo: 'LIG넥스원', kind: 'Enterprise', sector: 'Aerospace',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '1976',
    summary: 'Guided weapons and avionics.', summaryKo: '유도무기·항전 장비 기업입니다.',
    role: 'Shares avionics test records.', roleKo: '항전 시험 이력을 공유합니다.' },
  { name: 'Samsung Biologics', nameKo: '삼성바이오로직스', kind: 'Enterprise', sector: 'Bio',
    hq: 'Incheon', hqKo: '인천', founded: '2011',
    summary: 'Biopharmaceutical contract manufacturer.', summaryKo: '바이오의약품 위탁생산 기업입니다.',
    role: 'Publishes batch release records.', roleKo: '배치 출하 이력을 제공합니다.' },
  { name: 'Celltrion', nameKo: '셀트리온', kind: 'Enterprise', sector: 'Bio',
    hq: 'Incheon', hqKo: '인천', founded: '2002',
    summary: 'Biosimilar developer and maker.', summaryKo: '바이오시밀러 개발·생산 기업입니다.',
    role: 'Shares cold chain records.', roleKo: '콜드체인 이력을 공유합니다.' },
  { name: 'Samsung C&T', nameKo: '삼성물산', kind: 'Enterprise', sector: 'Construction',
    hq: 'Seoul', hqKo: '서울', founded: '1938',
    summary: 'Construction and trading group.', summaryKo: '건설·상사 기업입니다.',
    role: 'Publishes building material PCF.', roleKo: '건설자재 PCF를 제공합니다.' },
  { name: 'Hyundai E&C', nameKo: '현대건설', kind: 'Enterprise', sector: 'Construction',
    hq: 'Seoul', hqKo: '서울', founded: '1947',
    summary: 'Engineering and construction.', summaryKo: '엔지니어링·건설 기업입니다.',
    role: 'Shares site energy data.', roleKo: '현장 에너지 데이터를 공유합니다.' },
  { name: 'KIST', nameKo: '한국과학기술연구원', kind: 'Institute', sector: 'Research',
    hq: 'Seoul', hqKo: '서울', founded: '1966',
    summary: 'Korea\'s first multidisciplinary research institute.', summaryKo: '국내 최초 종합 연구기관입니다.',
    role: 'Runs joint materials research.', roleKo: '공동 소재 연구를 수행합니다.' },
  { name: 'ETRI', nameKo: '한국전자통신연구원', kind: 'Institute', sector: 'Research',
    hq: 'Daejeon', hqKo: '대전', founded: '1976',
    summary: 'ICT and electronics research institute.', summaryKo: 'ICT·전자 분야 연구기관입니다.',
    role: 'Develops connector standards.', roleKo: '커넥터 표준을 개발합니다.' },
  { name: 'KITECH', nameKo: '한국생산기술연구원', kind: 'Institute', sector: 'Research',
    hq: 'Cheonan', hqKo: '충남 천안', founded: '1989',
    summary: 'Production technology research institute.', summaryKo: '생산기술 전문 연구기관입니다.',
    role: 'Supports SME smart factories.', roleKo: '중소기업 스마트공장을 지원합니다.' },
  { name: 'KETI', nameKo: '한국전자기술연구원', kind: 'Institute', sector: 'Research',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '1991',
    summary: 'Electronics technology research institute.', summaryKo: '전자기술 전문 연구기관입니다.',
    role: 'Leads AI and mobility research.', roleKo: 'AI·모빌리티 연구를 주도합니다.' },
  { name: 'KIMS', nameKo: '한국재료연구원', kind: 'Institute', sector: 'Research',
    hq: 'Changwon', hqKo: '경남 창원', founded: '2007',
    summary: 'Materials science research institute.', summaryKo: '재료 분야 연구기관입니다.',
    role: 'Provides materials test data.', roleKo: '소재 시험 데이터를 제공합니다.' },
  { name: 'KERI', nameKo: '한국전기연구원', kind: 'Institute', sector: 'Research',
    hq: 'Changwon', hqKo: '경남 창원', founded: '1976',
    summary: 'Electrical engineering research institute.', summaryKo: '전기 분야 연구기관입니다.',
    role: 'Certifies electrical equipment.', roleKo: '전기설비를 시험·인증합니다.' },
  { name: 'KIMM', nameKo: '한국기계연구원', kind: 'Institute', sector: 'Research',
    hq: 'Daejeon', hqKo: '대전', founded: '1976',
    summary: 'Machinery and materials research institute.', summaryKo: '기계 분야 연구기관입니다.',
    role: 'Runs machinery reliability tests.', roleKo: '기계 신뢰성 시험을 수행합니다.' },
  { name: 'KRISS', nameKo: '한국표준과학연구원', kind: 'Institute', sector: 'Research',
    hq: 'Daejeon', hqKo: '대전', founded: '1975',
    summary: 'National metrology institute.', summaryKo: '국가 측정표준 기관입니다.',
    role: 'Provides measurement traceability.', roleKo: '측정 소급성을 제공합니다.' },
  { name: 'KISTI', nameKo: '한국과학기술정보연구원', kind: 'Institute', sector: 'Research',
    hq: 'Daejeon', hqKo: '대전', founded: '1962',
    summary: 'Science data and supercomputing institute.', summaryKo: '과학데이터·슈퍼컴퓨팅 기관입니다.',
    role: 'Operates the national data grid.', roleKo: '국가 데이터 그리드를 운영합니다.' },
  { name: 'KIER', nameKo: '한국에너지기술연구원', kind: 'Institute', sector: 'Research',
    hq: 'Daejeon', hqKo: '대전', founded: '1977',
    summary: 'Energy technology research institute.', summaryKo: '에너지기술 연구기관입니다.',
    role: 'Models plant energy efficiency.', roleKo: '공장 에너지 효율을 분석합니다.' },
  { name: 'KRICT', nameKo: '한국화학연구원', kind: 'Institute', sector: 'Research',
    hq: 'Daejeon', hqKo: '대전', founded: '1976',
    summary: 'Chemical technology research institute.', summaryKo: '화학 분야 연구기관입니다.',
    role: 'Provides chemical safety data.', roleKo: '화학물질 안전 데이터를 제공합니다.' },
  { name: 'KIOST', nameKo: '한국해양과학기술원', kind: 'Institute', sector: 'Research',
    hq: 'Busan', hqKo: '부산', founded: '1973',
    summary: 'Ocean science and technology institute.', summaryKo: '해양과학기술 연구기관입니다.',
    role: 'Supplies maritime environment data.', roleKo: '해양 환경 데이터를 공급합니다.' },
  { name: 'DGIST', nameKo: 'DGIST', kind: 'Academia', sector: 'Academia',
    hq: 'Daegu', hqKo: '대구', founded: '2004',
    summary: 'Science and technology research university.', summaryKo: '과학기술 연구중심 대학입니다.',
    role: 'Runs the robotics research node.', roleKo: '로보틱스 연구 노드를 운영합니다.' },
  { name: 'UNIST', nameKo: 'UNIST', kind: 'Academia', sector: 'Academia',
    hq: 'Ulsan', hqKo: '울산', founded: '2007',
    summary: 'Science and technology research university.', summaryKo: '과학기술 연구중심 대학입니다.',
    role: 'Runs the battery research node.', roleKo: '배터리 연구 노드를 운영합니다.' },
  { name: 'Kumoh National Institute of Technology', nameKo: '금오공과대학교', kind: 'Academia', sector: 'Academia',
    hq: 'Gumi', hqKo: '경북 구미', founded: '1980',
    summary: 'Engineering university in Gumi.', summaryKo: '구미 소재 공과대학입니다.',
    role: 'Trains the regional workforce.', roleKo: '지역 인력을 양성합니다.' },
  { name: 'Korea Maritime & Ocean University', nameKo: '한국해양대학교', kind: 'Academia', sector: 'Academia',
    hq: 'Busan', hqKo: '부산', founded: '1945',
    summary: 'Maritime and logistics university.', summaryKo: '해양·물류 특성화 대학입니다.',
    role: 'Researches port logistics.', roleKo: '항만 물류를 연구합니다.' },
  { name: 'KIAT', nameKo: '한국산업기술진흥원', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Seoul', hqKo: '서울', founded: '2009',
    summary: 'Industrial technology promotion agency.', summaryKo: '산업기술 진흥 전담기관입니다.',
    role: 'Funds dataspace programmes.', roleKo: '데이터스페이스 사업을 지원합니다.' },
  { name: 'KEIT', nameKo: '한국산업기술기획평가원', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Daegu', hqKo: '대구', founded: '2009',
    summary: 'Industrial R&D planning and evaluation.', summaryKo: '산업 R&D 기획·평가 기관입니다.',
    role: 'Evaluates industrial R&D.', roleKo: '산업 R&D를 평가합니다.' },
  { name: 'KOTRA', nameKo: '대한무역투자진흥공사', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Seoul', hqKo: '서울', founded: '1962',
    summary: 'Trade and investment promotion agency.', summaryKo: '무역·투자 진흥 공기업입니다.',
    role: 'Connects overseas partners.', roleKo: '해외 파트너를 연결합니다.' },
  { name: 'NIPA', nameKo: '정보통신산업진흥원', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Jincheon', hqKo: '충북 진천', founded: '2009',
    summary: 'ICT industry promotion agency.', summaryKo: 'ICT 산업 진흥기관입니다.',
    role: 'Supports AI adoption.', roleKo: 'AI 도입을 지원합니다.' },
  { name: 'KISA', nameKo: '한국인터넷진흥원', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Naju', hqKo: '전남 나주', founded: '2009',
    summary: 'Internet and information security agency.', summaryKo: '인터넷·정보보호 진흥기관입니다.',
    role: 'Operates identity trust anchors.', roleKo: '신원 신뢰 앵커를 운영합니다.' },
  { name: 'Korea Institute of Robot Industry Advancement', nameKo: '한국로봇산업진흥원', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Daegu', hqKo: '대구', founded: '2010',
    summary: 'Robot industry promotion agency.', summaryKo: '로봇산업 진흥기관입니다.',
    role: 'Certifies robot safety.', roleKo: '로봇 안전을 인증합니다.' },
  { name: 'KICOX Daegu-Gyeongbuk', nameKo: '한국산업단지공단 대경권본부', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Daegu', hqKo: '대구', founded: '1997',
    summary: 'Industrial complex operator.', summaryKo: '산업단지를 운영·지원합니다.',
    role: 'Runs smart complex programmes.', roleKo: '스마트산단 사업을 운영합니다.' },
  { name: 'Gumi Electronics & Information Technology Research Institute', nameKo: '구미전자정보기술원', kind: 'Institute', sector: 'Research',
    hq: 'Gumi', hqKo: '경북 구미', founded: '2007',
    summary: 'Regional electronics research institute.', summaryKo: '지역 전자정보 연구기관입니다.',
    role: 'Tests regional SME products.', roleKo: '지역 중소기업 제품을 시험합니다.' },
  { name: 'Daegu Technopark', nameKo: '대구테크노파크', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Daegu', hqKo: '대구', founded: '1998',
    summary: 'Regional innovation support agency.', summaryKo: '지역 혁신 지원기관입니다.',
    role: 'Runs regional pilot lines.', roleKo: '지역 실증 라인을 운영합니다.' },
  { name: 'Daegu Mechatronics & Materials Institute', nameKo: '대구기계부품연구원', kind: 'Institute', sector: 'Research',
    hq: 'Daegu', hqKo: '대구', founded: '2003',
    summary: 'Machinery and parts research institute.', summaryKo: '기계부품 연구기관입니다.',
    role: 'Tests machinery components.', roleKo: '기계 부품을 시험합니다.' },
  { name: 'Ulsan Technopark', nameKo: '울산테크노파크', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Ulsan', hqKo: '울산', founded: '2000',
    summary: 'Regional innovation support agency.', summaryKo: '지역 혁신 지원기관입니다.',
    role: 'Supports the Ulsan pilot plant.', roleKo: '울산 실증 플랜트를 지원합니다.' },
  { name: 'Ulsan Institute', nameKo: '울산연구원', kind: 'Institute', sector: 'Research',
    hq: 'Ulsan', hqKo: '울산', founded: '2001',
    summary: 'Regional policy research institute.', summaryKo: '지역 정책 연구기관입니다.',
    role: 'Studies regional industry policy.', roleKo: '지역 산업 정책을 연구합니다.' },
  { name: 'Busan Technopark', nameKo: '부산테크노파크', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Busan', hqKo: '부산', founded: '1999',
    summary: 'Regional innovation support agency.', summaryKo: '지역 혁신 지원기관입니다.',
    role: 'Supports port logistics pilots.', roleKo: '항만 물류 실증을 지원합니다.' },
  { name: 'Gyeonggi Business & Science Accelerator', nameKo: '경기도경제과학진흥원', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Suwon', hqKo: '경기 수원', founded: '2018',
    summary: 'Provincial industry promotion agency.', summaryKo: '경기도 산업 진흥기관입니다.',
    role: 'Runs the Pangyo cluster programme.', roleKo: '판교 클러스터 사업을 운영합니다.' },
  { name: 'Pangyo Techno Valley', nameKo: '판교테크노밸리', kind: 'Agency', sector: 'PublicAgency',
    hq: 'Seongnam', hqKo: '경기 성남', founded: '2005',
    summary: 'Korea\'s flagship innovation cluster.', summaryKo: '국내 대표 혁신 클러스터입니다.',
    role: 'Hosts the R&D node.', roleKo: 'R&D 노드를 유치합니다.' },
  { name: 'Korea', kind: 'Enterprise', sector: 'ICT' },
  { name: 'HYUNDAI', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'KIA', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'SAMSUNG', kind: 'Enterprise', sector: 'Electronics' },
  { name: 'LG', kind: 'Enterprise', sector: 'Electronics' },
  { name: 'SK', kind: 'Enterprise', sector: 'Energy' },
  { name: 'LG Energy Sol', kind: 'Enterprise', sector: 'Battery' },
  { name: 'S-Oil', kind: 'Enterprise', sector: 'Energy' },
  { name: 'KAI', kind: 'Enterprise', sector: 'Aerospace' },
  { name: 'Toyota', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'Denso', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'Fanuc', kind: 'Enterprise', sector: 'Robotics' },
  { name: 'Sony', kind: 'Enterprise', sector: 'Electronics' },
  { name: 'Mitsubishi', kind: 'Enterprise', sector: 'HeavyIndustry' },
  { name: 'Hitachi', kind: 'Enterprise', sector: 'Electronics' },
  { name: 'Softbank', kind: 'Enterprise', sector: 'ICT' },
  { name: 'SAP', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Siemens', kind: 'Enterprise', sector: 'Electronics' },
  { name: 'T-Systems', kind: 'Enterprise', sector: 'ICT' },
  { name: 'BMW Group', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'Cofinity-X', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Bosch', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'BASF', kind: 'Enterprise', sector: 'Chemicals' },
  { name: 'Fraunhofer ISST', kind: 'Institute', sector: 'Research' },
  { name: 'MHP', kind: 'Enterprise', sector: 'ICT' },
  { name: 'NTT DATA', kind: 'Enterprise', sector: 'ICT' },
  { name: 'AWS', kind: 'Enterprise', sector: 'ICT' },
  { name: 'IBM', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Sovity', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Ipoint', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Capgemini', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Mercedes-Benz', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'Continental', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'ZF', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'Circularise', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Glassdome', kind: 'Enterprise', sector: 'ICT' },
  { name: 'BearingPoint', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Kinaxis', kind: 'Enterprise', sector: 'ICT' },
  { name: 'e2open', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Tesla', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'General Motors', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'Ford', kind: 'Enterprise', sector: 'Automotive' },
  { name: 'NVIDIA', kind: 'Enterprise', sector: 'Semiconductor' },
  { name: 'Intel', kind: 'Enterprise', sector: 'Semiconductor' },
  { name: 'Microsoft', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Google Cloud', kind: 'Enterprise', sector: 'ICT' },
  { name: 'PSA Singapore', kind: 'Enterprise', sector: 'Logistics' },
  { name: 'Grab', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Shopee', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Singtel', kind: 'Enterprise', sector: 'ICT' },
  { name: 'Sea Group', kind: 'Enterprise', sector: 'ICT' },
];

const BY_NAME = new Map(DIRECTORY.map((e) => [e.name, e]));

export const lookupOrg = (name: string): DirectoryEntry | undefined => BY_NAME.get(name);

/** Sector of a name we have no entry for, so filtering never drops a member. */
export const sectorOf = (name: string): Sector => BY_NAME.get(name)?.sector ?? 'ICT';

