
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'KO' | 'EN';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Nav
    nav_overview: "Overview",
    nav_portal: "DS Portal",
    nav_framework: "Framework",
    nav_marketplace: "Marketplace",
    nav_myassets: "My Assets",
    nav_connector: "Connector Status",
    nav_usecases: "Use Cases",
    nav_demonstration: "Live Demo",
    nav_edc_sim: "EDC Simulator",
    nav_id_sim: "Identity Simulator",
    nav_guideline: "Guideline",
    nav_tutorial: "Tutorial",
    nav_blockchain: "Blockchain Lab",
    nav_clearinghouse: "Clearing House",
    nav_preprocessing: "Preprocessing",
    nav_energy: "Energy AI",
    nav_lang: "Language",
    nav_pcf: "PCF Tracking",
    nav_dpp: "Digital Passport (DPP)",
    nav_supplychain: "Supply Chain Map",
    nav_security: "Security & Sovereignty",
    
    // Portal
    pt_welcome: "Welcome to Korea DS Platform Portal",
    pt_search_ph: "Search extensions, themes, equipment, parts...",
    pt_categories: "Top Categories",
    pt_participants: "Participating Companies",
    pt_featured_products: "Featured Products & Services",
    pt_results: "Search Results",

    // Overview
    ov_title: "DataSpace Overview",
    ov_subtitle: "Real-time ecosystem insights and network performance.",
    ov_network_op: "Network Operational",
    ov_part_comp: "Participating Companies",
    ov_total_data: "Total Data Volume",
    ov_monthly_tx: "Monthly Transaction Vol",
    ov_global_conn: "Global Connectivity",
    ov_network_traffic: "Network Traffic (24h)",
    ov_industry_share: "Industry Share",
    ov_new_assets: "New Marketplace Assets",
    ov_view_all: "View All",
    ov_highest_growth: "Highest growth in",
    ov_sector: "sector this month.",
    ov_last_24h: "Last 24 Hours",
    ov_last_7d: "Last 7 Days",
    ov_last_30d: "Last 30 Days",
    ov_live_map: "Live Data Ecosystem Map",
    ov_live_feed: "Live Transactions",

    // Framework
    fw_title: "The challenge of endless possibilities",
    fw_subtitle: "Increase business productivity with manufacturing big data analysis and AI application with Korea",
    fw_card_framework: "Framework",
    fw_card_desc: "System Management Service",
    fw_view_details: "View Details",
    
    // Marketplace
    mp_title: "Marketplace",
    mp_subtitle: "Discover and trade industrial data assets & services.",
    mp_sort: "Sort",
    mp_create: "Create Asset",
    mp_core_ai: "Core AI Common Models",
    mp_search_ph: "Search for data, models, or apps...",
    mp_all_ind: "All Industries",
    mp_all_types: "All Asset Types",
    mp_no_assets: "No assets found",
    mp_try_adjust: "Try adjusting your search or filters.",

    // Asset Detail
    ad_back: "Back to Marketplace",
    ad_desc: "Description",
    ad_data_vol: "Data Volume",
    ad_trust: "Trust Level",
    ad_tech_spec: "Technical Specifications (AAS)",
    ad_sub_price: "Subscription Price",
    ad_buy: "Buy Now",
    ad_processing: "Processing Contract...",
    ad_signed: "Contract Signed!",
    ad_access: "Access Data Stream",
    ad_provider_info: "Provider Info",
    ad_member_since: "Member since",
    ad_certified: "Certified Provider",
    ad_standard: "Standard",
    ad_entries: "entries",
    ad_secured: "Secured via Blockchain Contract",
    ad_instant: "Instant Access via EDC Connector",

    // Dashboard
    db_title: "My Assets & Wallet",
    db_connector_active: "EDC Connector Active",
    db_uptime: "Uptime",
    db_total_vol: "Total Data Volume",
    db_active_contracts: "Active Contracts",
    db_api_calls: "API Calls",
    db_est_rev: "Est. Revenue",
    db_data_transfer: "Data Transfer Volume",
    db_smart_contracts: "Smart Contracts",
    db_view_tx: "View All Transactions",
    db_balance: "Total Balance",
    db_income: "Monthly Income",
    db_expense: "Monthly Expenses",
    db_my_library: "My Library",
    db_active_sub: "Active Subscriptions",
    db_renewal: "Next Renewal",
    db_topup: "Top Up",
    db_topup_success: "Wallet recharged successfully!",
    db_topup_modal_title: "Top Up Balance",
    db_select_amount: "Select Amount",
    db_custom_amount: "Custom Amount",
    db_confirm_charge: "Charge Wallet",

    // Use Cases
    uc_title: "Industry Success Stories",
    uc_subtitle: "See how leading global companies are innovating with Korea DataSpace.",
    uc_roadmap_title: "DataSpace Adoption Roadmap",
    uc_step_1_title: "Consultation",
    uc_step_1_desc: "Analyze business needs and identify high-impact data exchange scenarios.",
    uc_step_2_title: "Onboarding",
    uc_step_2_desc: "Register company profile and obtain verified digital identity (VC).",
    uc_step_3_title: "Integration",
    uc_step_3_desc: "Install EDC connector and map internal data to standard models (AAS).",
    uc_step_4_title: "Innovation",
    uc_step_4_desc: "Start secure data trading and create new value with partners.",
    
    // Demonstration
    demo_title: "DataSpace Live Demonstration",
    demo_subtitle: "Experience the real-time flow of data sovereignty and exchange.",

    // Guideline
    gl_title: "DataSpace Guideline",
    gl_subtitle: "Governance, Architecture, and Operational Standards for the Industrial Data Ecosystem.",
    
    // Tutorial
    tut_title: "Platform Tutorials",
    tut_subtitle: "Step-by-step guides to master the Korea DataSpace Platform.",

    // Blockchain Lab
    bl_title: "Blockchain Lab",
    bl_subtitle: "Visualize and simulate decentralized data transactions on the ledger.",
    bl_tx_simulator: "Transaction Simulator",
    bl_select_asset: "Select Asset to Buy",
    bl_exec_contract: "Execute Smart Contract",
    bl_processing: "Processing...",
    bl_consensus_flow: "Consensus Flow",
    bl_live_ledger: "Live Blockchain Ledger",
    bl_scenario: "Scenario Mode",
    bl_scen_normal: "Normal Approval",
    bl_scen_funds: "Reject: Low Balance",
    bl_scen_policy: "Reject: Policy Violation",
    bl_scen_manual: "Manual Review",
    bl_scen_manual_fail: "Manual Review (Low Funds)",
    bl_manual_review_req: "Approval Required",
    bl_approve: "Approve",
    bl_reject: "Reject",
    bl_waiting: "Waiting for Input...",
    bl_low_balance_title: "Insufficient Balance",
    bl_low_balance_msg: "Smart contract execution failed due to insufficient funds/gas. Please recharge your wallet.",
    bl_go_wallet: "Go to Wallet",
    bl_approve_low_funds: "Approve (Simulate Low Funds)",

    // Clearing House
    ch_title: "Clearing House",
    ch_subtitle: "Identity verification and transaction settlement service for DataSpace Trust.",
    ch_kpi_participants: "Verified Participants",
    ch_kpi_settlement: "Total Settlement",
    ch_kpi_transactions: "Cleared Transactions",
    ch_tab_identity: "Identity & Trust",
    ch_tab_financial: "Financial Clearing",
    ch_tab_simulation: "Verification Simulator",
    ch_pending_verifications: "Pending Verifications",
    ch_verified_list: "Verified Partners List",
    ch_verify: "Verify",
    ch_sim_title: "Identity Verification Simulator",
    ch_sim_desc: "Simulate the KYB (Know Your Business) and VC issuance process for a new participant.",
    ch_sim_step_1: "Registry Check",
    ch_sim_step_2: "Compliance Check",
    ch_sim_step_3: "VC Issuance",
    ch_sim_step_4: "Blockchain Anchor",
    ch_sim_start: "Start Verification",
    ch_sim_reset: "Reset",
    ch_sim_company: "Company Name",
    ch_sim_logs: "System Logs",
    ch_sim_scen_success: "Success: Verified Credential Issued",
    ch_sim_scen_fail_reg: "Fail: Registry Lookup Failed",
    ch_sim_scen_fail_comp: "Fail: Sanctions List Detected",
    ch_res_success_title: "Verification Successful",
    ch_res_fail_title: "Verification Rejected",
    ch_modal_success_msg: "Verifiable Credential (VC) has been successfully issued and anchored to the blockchain.",
    ch_modal_fail_msg: "Verification failed due to compliance or registry issues.",
    ch_modal_save: "Save JSON",
    ch_modal_share: "Share",
    ch_modal_try_again: "Try Again",
    ch_modal_subject: "Subject",
    ch_modal_did: "DID",
    ch_modal_issued: "Issued",
    ch_modal_expiry: "Expiry",
    ch_modal_reason: "Reason for Rejection",
    ch_modal_error_code: "Error Code",

    // Preprocessing
    pp_title: "Data Preprocessing",
    pp_subtitle: "Automated cleaning and feature engineering pipeline for industrial data.",
    pp_step_upload: "Upload Data",
    pp_step_config: "Configure Pipeline",
    pp_step_result: "Results",
    pp_upload_drag: "Drag & Drop your dataset",
    pp_upload_desc: "Supports CSV, Excel, Parquet (Max 100MB)",
    pp_btn_browse: "Browse Files",
    pp_btn_remove: "Remove File",
    pp_pipeline_config: "Pipeline Configuration",
    pp_opt_missing: "Missing Value Imputation",
    pp_opt_outlier: "Outlier Removal",
    pp_opt_norm: "Normalization",
    pp_opt_noise: "Noise Reduction",
    pp_btn_run: "Run Automation",
    pp_processing: "Processing Data...",
    pp_processing_desc: "Applying algorithms...",
    pp_res_chart: "Before / After Comparison",
    pp_res_preview: "Data Preview",
    pp_stats_title: "Quality Report",
    pp_btn_download: "Download Cleaned Data",
    pp_btn_save_asset: "Save as Asset",
    pp_btn_new: "New Project",
    pp_mode_sme: "SME Mode",
    pp_mode_ent: "Enterprise Mode",
    pp_sme_auto_title: "Smart Auto-Pilot",
    pp_sme_auto_desc: "AI Auto-Detection",
    pp_ent_manual_title: "Engineer Control",
    pp_metric_completeness: "Completeness",
    pp_metric_accuracy: "Accuracy",
    pp_metric_consistency: "Consistency",
    pp_metric_uniqueness: "Uniqueness",
    pp_metric_validity: "Validity",
    pp_export_excel: "Excel Download",
    pp_export_cloud: "Save to Cloud",
    pp_export_email: "Email Report",
    pp_export_api: "Create Hosted API",
    pp_export_api_desc: "Generate a secure, platform-hosted API endpoint for your data.",

    // Energy Module
    en_title: "Energy Optimization AI",
    en_subtitle: "Real-time monitoring and AI-driven energy efficiency management.",
    en_autopilot: "AI Auto-Pilot",
    en_kpi_usage: "Current Power",
    en_kpi_carbon: "Carbon Emission",
    en_kpi_solar: "Renewable Mix",
    en_kpi_savings: "Est. Monthly Savings",
    en_chart_title: "Real-time Energy Consumption vs Baseline",
    en_zone_title: "Factory Zone Efficiency Status",
    en_ai_actions: "Optimization Opportunities",

    // Supply Chain Map
    scm_title: "Supply Chain Map",
    scm_subtitle: "Visualize the DataSpace ecosystem from Tier-N to OEM.",
    scm_legend: "Supply Chain Legend",
    scm_tier: "Tier",
    scm_oem: "OEM",
    scm_risk: "Risk Level",
    scm_carbon: "Carbon Footprint",
    scm_compliance: "Compliance",
    scm_click_details: "Click a node to view details",

    // Common
    c_provider: "Provider",
    c_price: "Price",
    c_close: "Close",
  },
  KO: {
    // Nav
    nav_overview: "개요",
    nav_portal: "DS 포털",
    nav_framework: "프레임워크",
    nav_marketplace: "마켓플레이스",
    nav_myassets: "내 자산",
    nav_connector: "커넥터 상태",
    nav_usecases: "활용 사례",
    nav_demonstration: "실증 시나리오",
    nav_edc_sim: "EDC 시뮬레이터",
    nav_id_sim: "신원인증 시뮬레이터",
    nav_guideline: "가이드라인",
    nav_tutorial: "튜토리얼",
    nav_blockchain: "블록체인 실험실",
    nav_clearinghouse: "클리어링 하우스",
    nav_preprocessing: "전처리 자동화",
    nav_energy: "에너지 최적화",
    nav_lang: "언어",
    nav_pcf: "PCF 트래커",
    nav_dpp: "디지털 여권 (DPP)",
    nav_supplychain: "공급망 지도",
    nav_security: "보안 및 데이터 주권",

    // Portal
    pt_welcome: "Korea DS Platform Portal에 오신 것을 환영합니다",
    pt_search_ph: "확장 프로그램, 테마, 설비, 부품 검색...",
    pt_categories: "상위 카테고리",
    pt_participants: "참여 기업 (Participants)",
    pt_featured_products: "추천 제품 및 서비스",
    pt_results: "검색 결과",

    // Overview
    ov_title: "데이터스페이스 개요",
    ov_subtitle: "실시간 생태계 통찰력 및 네트워크 성능.",
    ov_network_op: "네트워크 정상 작동",
    ov_part_comp: "참여 기업",
    ov_total_data: "총 데이터 용량",
    ov_monthly_tx: "월간 거래량",
    ov_global_conn: "글로벌 연결성",
    ov_network_traffic: "네트워크 트래픽 (24시간)",
    ov_industry_share: "산업 점유율",
    ov_new_assets: "신규 마켓플레이스 자산",
    ov_view_all: "모두 보기",
    ov_highest_growth: "이번 달 최대 성장:",
    ov_sector: "분야.",
    ov_last_24h: "지난 24시간",
    ov_last_7d: "지난 7일",
    ov_last_30d: "지난 30일",
    ov_live_map: "실시간 데이터 생태계 맵",
    ov_live_feed: "실시간 트랜잭션",

    // Framework
    fw_title: "무한한 가능성을 향한 도전",
    fw_subtitle: "Korea의 제조 빅데이터 분석 및 AI 애플리케이션으로 비즈니스 생산성을 높이세요",
    fw_card_framework: "프레임워크",
    fw_card_desc: "시스템 관리 서비스",
    fw_view_details: "상세 보기",

    // Marketplace
    mp_title: "마켓플레이스",
    mp_subtitle: "산업용 데이터 자산 및 서비스를 탐색하고 거래하세요.",
    mp_sort: "정렬",
    mp_create: "자산 등록",
    mp_core_ai: "핵심 AI 공통 모델",
    mp_search_ph: "데이터, 모델, 앱 검색...",
    mp_all_ind: "모든 산업",
    mp_all_types: "모든 자산 유형",
    mp_no_assets: "자산을 찾을 수 없습니다",
    mp_try_adjust: "검색어나 필터를 조정해보세요.",

    // Asset Detail
    ad_back: "마켓플레이스로 돌아가기",
    ad_desc: "설명",
    ad_data_vol: "데이터 용량",
    ad_trust: "신뢰 수준",
    ad_tech_spec: "기술 사양 (AAS)",
    ad_sub_price: "구독 가격",
    ad_buy: "구매하기",
    ad_processing: "계약 처리 중...",
    ad_signed: "계약 체결 완료!",
    ad_access: "데이터 스트림 접속",
    ad_provider_info: "제공자 정보",
    ad_member_since: "가입일",
    ad_certified: "인증된 제공자",
    ad_standard: "일반",
    ad_entries: "건",
    ad_secured: "블록체인 계약으로 보안됨",
    ad_instant: "EDC 커넥터를 통한 즉시 접속",

    // Dashboard
    db_title: "내 자산 & 지갑",
    db_connector_active: "EDC 커넥터 활성",
    db_uptime: "가동 시간",
    db_total_vol: "총 데이터 용량",
    db_active_contracts: "활성 계약",
    db_api_calls: "API 호출",
    db_est_rev: "예상 수익",
    db_data_transfer: "데이터 전송량",
    db_smart_contracts: "스마트 계약",
    db_view_tx: "모든 거래 보기",
    db_balance: "총 잔액",
    db_income: "이번 달 수입",
    db_expense: "이번 달 지출",
    db_my_library: "나의 라이브러리",
    db_active_sub: "구독 중인 서비스",
    db_renewal: "다음 갱신일",
    db_topup: "잔액 충전",
    db_topup_success: "지갑이 성공적으로 충전되었습니다!",
    db_topup_modal_title: "잔액 충전",
    db_select_amount: "충전 금액 선택",
    db_custom_amount: "직접 입력",
    db_confirm_charge: "충전하기",

    // Use Cases
    uc_title: "산업별 성공 사례",
    uc_subtitle: "글로벌 선도 기업들이 Korea 데이터스페이스를 통해 어떻게 혁신하고 있는지 확인하세요.",
    uc_roadmap_title: "데이터스페이스 도입 로드맵",
    uc_step_1_title: "도입 상담 (Consultation)",
    uc_step_1_desc: "기업의 데이터 보유 현황을 진단하고, 데이터 교환을 통해 창출할 수 있는 비즈니스 가치를 발굴합니다.",
    uc_step_2_title: "온보딩 (Onboarding)",
    uc_step_2_desc: "Korea 포털에 기업을 등록하고, 신뢰할 수 있는 디지털 신원(VC)을 발급받아 네트워크 참여 자격을 획득합니다.",
    uc_step_3_title: "기술 연동 (Integration)",
    uc_step_3_desc: "EDC 커넥터를 설치하고 레거시 시스템과 연결합니다. AAS 표준에 맞춰 데이터를 자산화합니다.",
    uc_step_4_title: "가치 창출 (Innovation)",
    uc_step_4_desc: "안전한 데이터 거래를 시작하고, 파트너와 함께 새로운 비즈니스 모델과 혁신을 만들어갑니다.",

    // Demonstration
    demo_title: "데이터스페이스 실증 시나리오",
    demo_subtitle: "데이터 주권 보호 및 교환의 전 과정을 실시간으로 경험하세요.",

    // Guideline
    gl_title: "데이터스페이스 가이드라인",
    gl_subtitle: "산업 데이터 생태계를 위한 거버넌스, 아키텍처 및 운영 표준.",

    // Tutorial
    tut_title: "플랫폼 튜토리얼",
    tut_subtitle: "Korea 데이터스페이스 플랫폼 마스터를 위한 단계별 가이드.",
    
    // Blockchain Lab
    bl_title: "블록체인 실험실",
    bl_subtitle: "분산 원장(Ledger) 상의 데이터 거래를 시각화하고 시뮬레이션하세요.",
    bl_tx_simulator: "트랜잭션 시뮬레이터",
    bl_select_asset: "구매할 자산 선택",
    bl_exec_contract: "스마트 컨트랙트 실행",
    bl_processing: "처리 중...",
    bl_consensus_flow: "합의 및 처리 흐름",
    bl_live_ledger: "실시간 블록체인 원장",
    bl_scenario: "시나리오 모드",
    bl_scen_normal: "정상 승인",
    bl_scen_funds: "거절: 잔액 부족",
    bl_scen_policy: "거절: 정책 위반 (지역 제한)",
    bl_scen_manual: "수동 검토",
    bl_scen_manual_fail: "수동 검토 (잔액 부족)",
    bl_manual_review_req: "승인 필요",
    bl_approve: "승인",
    bl_reject: "거절",
    bl_waiting: "사용자 입력 대기 중...",
    bl_low_balance_title: "잔액 부족",
    bl_low_balance_msg: "스마트 컨트랙트 실행에 필요한 가스비 또는 자산 구매 비용이 부족합니다.",
    bl_go_wallet: "충전하러 가기",
    bl_approve_low_funds: "승인 (잔액 부족 시뮬레이션)",

    // Clearing House
    ch_title: "클리어링 하우스",
    ch_subtitle: "데이터스페이스 신뢰 보장을 위한 신원 검증 및 거래 정산 서비스.",
    ch_kpi_participants: "검증된 참여 기업",
    ch_kpi_settlement: "총 정산 금액",
    ch_kpi_transactions: "정산 완료 건수",
    ch_tab_identity: "신원 및 신뢰 관리",
    ch_tab_financial: "거래 정산 관리",
    ch_tab_simulation: "검증 시뮬레이터",
    ch_pending_verifications: "승인 대기 중인 검증 요청",
    ch_verified_list: "검증된 파트너 목록",
    ch_verify: "검증 승인",
    ch_sim_title: "신원 검증 시뮬레이터",
    ch_sim_desc: "신규 참여자의 KYB(기업 신원 확인) 및 VC(자격증명) 발급 프로세스를 시뮬레이션합니다.",
    ch_sim_step_1: "법인 등기부 조회",
    ch_sim_step_2: "컴플라이언스 체크",
    ch_sim_step_3: "VC(자격증명) 발급",
    ch_sim_step_4: "블록체인 앵커링",
    ch_sim_start: "검증 시작",
    ch_sim_reset: "초기화",
    ch_sim_company: "기업명",
    ch_sim_logs: "시스템 로그",
    ch_sim_scen_success: "정상 승인: 자격증명 발급",
    ch_sim_scen_fail_reg: "거절: 등기부 조회 실패",
    ch_sim_scen_fail_comp: "거절: 제재 대상자 발견",
    ch_res_success_title: "신원 검증 완료",
    ch_res_fail_title: "신원 검증 거절됨",
    ch_modal_success_msg: "검증된 자격 증명(VC)이 성공적으로 발급되어 블록체인에 앵커링되었습니다.",
    ch_modal_fail_msg: "규정 준수 또는 등기부 조회 문제로 인해 검증에 실패했습니다.",
    ch_modal_save: "JSON 저장",
    ch_modal_share: "공유하기",
    ch_modal_try_again: "다시 시도",
    ch_modal_subject: "발급 대상",
    ch_modal_did: "DID 식별자",
    ch_modal_issued: "발급일",
    ch_modal_expiry: "만료일",
    ch_modal_reason: "거절 사유",
    ch_modal_error_code: "오류 코드",

    // Preprocessing
    pp_title: "데이터 전처리 자동화",
    pp_subtitle: "산업용 데이터를 위한 자동화된 클리닝 및 특징 공학 파이프라인.",
    pp_step_upload: "데이터 업로드",
    pp_step_config: "파이프라인 설정",
    pp_step_result: "결과 확인",
    pp_upload_drag: "데이터셋을 이곳에 드래그하세요",
    pp_upload_desc: "CSV, Excel, Parquet 지원 (최대 100MB)",
    pp_btn_browse: "파일 찾기",
    pp_btn_remove: "파일 제거",
    pp_pipeline_config: "전처리 옵션 설정",
    pp_opt_missing: "결측치 처리 (Imputation)",
    pp_opt_outlier: "이상치 제거 (Outlier Removal)",
    pp_opt_norm: "정규화 (Normalization)",
    pp_opt_noise: "노이즈 제거 (Noise Reduction)",
    pp_btn_run: "자동화 실행",
    pp_processing: "데이터 처리 중...",
    pp_processing_desc: "알고리즘 적용 중입니다...",
    pp_res_chart: "전후 데이터 비교",
    pp_res_preview: "데이터 미리보기",
    pp_stats_title: "품질 리포트",
    pp_btn_download: "전처리된 데이터 다운로드",
    pp_btn_save_asset: "자산으로 저장",
    pp_btn_new: "새 프로젝트",
    pp_mode_sme: "중소기업 모드",
    pp_mode_ent: "대기업 모드",
    pp_sme_auto_title: "스마트 오토파일럿",
    pp_sme_auto_desc: "AI 자동 이상 탐지",
    pp_ent_manual_title: "엔지니어 정밀 제어",
    pp_metric_completeness: "완전성",
    pp_metric_accuracy: "정확성",
    pp_metric_consistency: "일관성",
    pp_metric_uniqueness: "유일성",
    pp_metric_validity: "유효성",
    pp_export_excel: "엑셀 다운로드",
    pp_export_cloud: "클라우드 저장",
    pp_export_email: "이메일 리포트",
    pp_export_api: "Hosted API 생성",
    pp_export_api_desc: "서버 없이 데이터를 안전하게 공유할 수 있는 API 엔드포인트를 생성합니다.",

    // Energy Module
    en_title: "에너지 최적화 AI",
    en_subtitle: "실시간 모니터링 및 AI 기반 에너지 효율 관리.",
    en_autopilot: "AI 오토파일럿",
    en_kpi_usage: "현재 전력 부하",
    en_kpi_carbon: "탄소 배출량",
    en_kpi_solar: "재생에너지 비율",
    en_kpi_savings: "예상 월 절감액",
    en_chart_title: "실시간 전력 소비량 vs 기준선",
    en_zone_title: "공장 구역별 효율 상태",
    en_ai_actions: "최적화 제안",

    // Supply Chain Map
    scm_title: "공급망 지도 (Supply Chain Map)",
    scm_subtitle: "데이터스페이스 생태계 내 Tier-N 부터 OEM 까지의 흐름을 시각화합니다.",
    scm_legend: "범례",
    scm_tier: "티어",
    scm_oem: "OEM (최종 기업)",
    scm_risk: "리스크 레벨",
    scm_carbon: "탄소 배출량",
    scm_compliance: "규정 준수",
    scm_click_details: "노드를 클릭하여 상세 정보를 확인하세요",

    // Common
    c_provider: "제공자",
    c_price: "가격",
    c_close: "닫기",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('KO');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'KO' ? 'EN' : 'KO'));
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
